### ISSUE TITLE
No feedback upon entering false credentials

### ISSUE THREAD

**Issue by berserkingyadis** [Levitanious/tempest-cms#1]
When trying to log into site (and giving bogus information) there should be some kind of feedback that the login attempt failed.

**Comment by Levitanious** [comment]
That would mean writing a SPECIAL PAGE FOR IT? INSTEAD OF JUST DOING `self.redirect("/")`?!

**Comment by berserkingyadis** [comment]
Or implementing a small "feedback" portion in the UI which pops up if something happens like:

- "you just registered! check your email spam-folder" in green
- "type your password correctly!" in red

feedback to the user is important

**Comment by Levitanious** [comment]
There's no better school than old school.

**Comment by Levitanious** [comment]
@berserkingyadis Basically, we'll need #21 for that. And because i've had no such machinery in place - i did everything as it is now.
